version: 2.0.0.{build}
configuration: Release
init:
  - ps: $env:GIT_SHORT_HASH = $env:APPVEYOR_REPO_COMMIT.substring(0,7)
before_build:
  - ps: dotnet --version
build_script:
  - ps: dotnet build
after_build:
  - ps: nuget pack "$env:APPVEYOR_BUILD_FOLDER\ExpressionEvaluator\ExpressionEvaluator.csproj" -Properties "Configuration=Release;Platform=AnyCPU" -Version $env:APPVEYOR_BUILD_VERSION
artifacts:
  - path: '**\*.nupkg'
deploy:
  - provider: NuGet
    api_key:
      secure: lUq2fMKbldj6txOnhMNVhDjhCzMrKDGeAGzE18pralInWqgK0AULnGMIwDxcBJ1p
    on:
      branch: release
