version: 2.0.1.{build}
image: Visual Studio 2019
configuration: Release
init:
  - ps: $env:GIT_SHORT_HASH = $env:APPVEYOR_REPO_COMMIT.substring(0,7)
before_build:
  - ps: dotnet --version
build_script:
  - ps: dotnet build --configuration Release -p:Version=$env:APPVEYOR_BUILD_VERSION
test_script:
  - ps: dotnet test --configuration Release -p:Version=$env:APPVEYOR_BUILD_VERSION
artifacts:
  - path: '**\*.nupkg'
deploy:
  - provider: NuGet
    api_key:
      secure: lUq2fMKbldj6txOnhMNVhDjhCzMrKDGeAGzE18pralInWqgK0AULnGMIwDxcBJ1p
    on:
      branch: master
